[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex_exchange = "9EqVh33gZ9Q2rG5kSyWWrMAvKgrXakoPXavPZucqQ3P8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
